num1 : float  = float(input("Enter 1st Number: "))
num2 : float  = float(input("Enter 1st Number: "))
print("Addition: ", num1 + num2)
print("Subtraction: ", num1 - num2)
print("Multiplication: ", num1 * num2)
print("Division: ", num1 / num2)
print("Floor Division: ", num1 // num2)
print("Modulus (Remainder): ", num1 % num2)
print("Power: ", num1 ** num2)